guilds:
- name: NAPS 
  roles:
    relevantParsing: true
    relevantFlexing: true
    legend: true
    ultimateFlexing: true
    datacenter: true
  guildId: 1008845758805594173
  channelId: 1008850017185955850
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [87]
    name: "P8SP2"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P8SP2-Cleared"
        type: "Cleared"
        color: 0xd06fa4
  - ids: [86]
    name: "P8SP1"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P8SP1-Cleared"
        type: "Cleared"
        color: 0xef8633
  - ids: [85]
    name: "P7S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P7S-Cleared"
        type: "Cleared"
        color: 0x9644e5
  - ids: [84]
    name: "P6S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P6S-Cleared"
        type: "Cleared"
        color: 0x2a72f6
  - ids: [83]
    name: "P5S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P5S-Cleared"
        type: "Cleared"
        color: 0x78fa4c
    clearedColor: 0x78fa4c
- name: APD 
  roles:
    relevantParsing: true
    relevantFlexing: true
    legend: true
    ultimateFlexing: true
    datacenter: true
  guildId: 968960259081252884
  channelId: 972868045552877589
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared"
        type: "Cleared"
        color: 0xf58cba
    prog:
    - name: Vault Knights
      color: 0x9C491B
      hoist: false
    - name: Thordan
      color: 0x693986
      hoist: false
      mention: false
    - name: Nidstinien
      color: 0x356590
      hoist: false
      mention: false
    - name: The Eyes
      color: 0x596D79
      hoist: false
      mention: false
    - name: Thordan Reprise
      color: 0x925CB1
      hoist: false
      mention: false
    - name: Double Dragon
      color: 0x5195D3
      hoist: false
      mention: false
    - name: Dragon-king Thordan
      color: 0xE8C444
      hoist: false
      mention: false
- name: UAR
  roles:
    relevantParsing: true
    relevantFlexing: false
    legend: true
    ultimateFlexing: true
    datacenter: true
  guildId: 973884326515191838
  channelId: 1028344695597838356
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    roles:
      - name: "UCoB Cleared"
        type: "Cleared"
        color: 0xFFFD7F
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    roles:
      - name: "UWU Cleared"
        type: "Cleared"
        color: 0x9CBDD8
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    roles:
      - name: "TEA Cleared"
        type: "Cleared"
        color: 0xFAE9C2
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "DSR Cleared"
        type: "Cleared"
        color: 0xCF8035
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    roles:
      - name: "TOP Cleared"
        type: "Cleared"
        color: 0xd1e5f4
- name: UDR
  roles:
    relevantParsing: true
    relevantFlexing: false
    legend: true
    ultimateFlexing: true
    datacenter: true
  guildId: 1021602454716022845
  channelId: 1037083485543866479
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    roles:
      - name: "i killed ucob"
        type: "Cleared"
        color: 0xb89c00
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    roles:
      - name: "i killed uwu"
        type: "Cleared"
        color: 0x23f3f7
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    roles:
      - name: "i killed tea"
        type: "Cleared"
        color: 0xf5cbff
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "i killed dsr"
        type: "Cleared"
        color: 0xD8833B
  reconfigureRoles:
  - from: "The Quad Legend"
    to: "dodge on sight"
    color: 0xff0003
- name: UPR
  roles:
    relevantParsing: false
    relevantFlexing: false
    legend: false
    ultimateFlexing: false
    datacenter: true
  guildId: 404710160540368917
  channelId: 1028389598755311657
  physicalDatacenters:
  - name: "NA"
    logicalDatacenters:
      - to: "aether guest"
        from: "Aether"
        color: 0x000001
      - to: "crystal guest"
        from: "Crystal"
        color: 0xf9c9a9
      - to: "primal guest"
        from: "Primal"
        color: 0xff0000
      - to: "dynamis guest"
        from: "Dynamis"
        color: 0xEAC645
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared Ucob"
        type: "Cleared"
        color: 0xEAC645
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared UwU"
        type: "Cleared"
        color: 0x3bbdf5
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared TEA"
        type: "Cleared"
        color: 0x65C97A
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared DSR"
        type: "Cleared"
        color: 0xb660ff
- name: Ultimate Uncoiled
  roles:
    relevantParsing: false
    relevantFlexing: true
    legend: true
    ultimateFlexing: false
    datacenter: false
    skipRemoval: true
  guildId: 556243090256560129
  channelId: 1052040182330822727
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared ucob"
        type: "Cleared"
        color: 0xf8ff00
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared uwu"
        type: "Cleared"
        color: 0x30d2fb
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared tea"
        type: "Cleared"
        color: 0x2daf55
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared dru"
        type: "Cleared"
        color: 0xe67cba
  reconfigureRoles:
  - from: "NA's Comfiest"
    to: "comfiest"
  - from: "Nice"
    to: "nice"
  - from: "Chad"
    to: "chad"
  - from: "Bloodbather"
    to: "bloodbather"
  - from: "Overhealer"
    to: "overhealer"
  - from: "Rainbow"
    to: "rainbow"
  - from: "The Man"
    to: "the man"
    dontSkip: true
  - from: "The Myth"
    to: "the myth"
    dontSkip: true
  - from: "The Uncoiled Legend"
    to: "the legend"
    dontSkip: true
  - from: "The Legend"
    skip: true
  - from: "The Double Legend"
    skip: true
  - from: "The Triple Legend"
    to: "triplelegendbtw"
    color: 0xb57edc
  - from: "The Quad Legend"
    to: "tetrislegendbtw"
    color: 0xffa6c9
- name: TOP
  roles:
    relevantParsing: true
    relevantFlexing: false
    legend: false
    ultimateFlexing: false
    datacenter: true
  guildId: 982459453578285056
  channelId: 1073363433489170442
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    roles:
      - name: "ALPHA LEGEND"
        type: "Cleared"
        color: 0xf58cba
        hoist: true
    prog:
    - name: Omega
      color: 0x693986
      hoist: true
    - name: Omega-M/F
      color: 0x356590
      hoist: true
    - name: Omega Reconfigured
      color: 0x596D79
      hoist: true
    - name: Blue Screen
      color: 0x925CB1
      hoist: true
    - name: "Run: Dynamis"
      color: 0x6fd9f3
      hoist: true
    - name: Alpha Omega
      color: 0xE8C444
      hoist: true
