encounters:
- ids: [87]
  name: "P8SP2"
  difficulty: "Savage"
  createRoles: true
  clearedColor: 0xd06fa4
- ids: [86]
  name: "P8SP1"
  difficulty: "Savage"
  createRoles: true
  clearedColor: 0xef8633
- ids: [85]
  name: "P7S"
  difficulty: "Savage"
  createRoles: true
  clearedColor: 0x9644e5
- ids: [84]
  name: "P6S"
  difficulty: "Savage"
  createRoles: true
  clearedColor: 0x2a72f6
- ids: [83]
  name: "P5S"
  difficulty: "Savage"
  createRoles: true
  clearedColor: 0x78fa4c

