# fly.toml app configuration file generated for clearingway on 2023-06-10T09:25:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clearingway"
primary_region = "lax"

[build]
  image = "ghcr.io/veraticus/clearingway:main"
